import mongoose from "mongoose";

// ----------------------------------------------------------------------
// Memora Backend — Digest model
// One document per digest actually sent (generated by
// jobs/generateDigest.job.js). Stores a SNAPSHOT of each commitment's
// text/due/urgency at send time, not a live reference — a digest from
// three weeks ago should still read exactly as it did when it arrived,
// even if the commitment has since been kept, snoozed, or edited.
// ----------------------------------------------------------------------

const digestItemSchema = new mongoose.Schema(
  {
    commitmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Commitment",
      required: true,
    },
    // Snapshot fields — deliberately duplicated from Commitment at the
    // moment the digest was generated. See note above.
    text: { type: String, required: true },
    due: { type: String, required: true }, // pre-formatted display string, e.g. "Today, 6:00 PM"
    urgency: {
      type: String,
      enum: ["overdue", "today", "upcoming", "stale", "kept"],
      required: true,
    },
  },
  { _id: false }
);

const digestSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    channel: {
      type: String,
      enum: ["email", "push", "both"],
      required: true,
    },

    // Stats shown on DigestCard.jsx's collapsed row
    stats: {
      overdue: { type: Number, default: 0 },
      dueToday: { type: Number, default: 0 },
      kept: { type: Number, default: 0 },
    },

    items: [digestItemSchema],

    sentAt: {
      type: Date,
      required: true,
      default: Date.now,
    },

    // Whether the user opened the email / tapped the push notification
    // — useful signal for tuning delivery time later.
    openedAt: { type: Date },

    // True if triggered by digestApi.sendNow() (manual/testing) rather
    // than the scheduled job — kept for support/debugging visibility.
    isManualSend: { type: Boolean, default: false },
  },
  { timestamps: true }
);

digestSchema.index({ userId: 1, sentAt: -1 });

// ---- Derived display fields (DigestCard.jsx / DigestList.jsx shape) -----
digestSchema.virtual("dayLabel").get(function getDayLabel() {
  const sent = new Date(this.sentAt);
  const now = new Date();
  const startOf = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate());
  const diffDays = Math.round((startOf(now) - startOf(sent)) / (24 * 60 * 60 * 1000));

  if (diffDays === 0) return "Today";
  if (diffDays === 1) return "Yesterday";
  return sent.toLocaleDateString(undefined, { month: "short", day: "numeric" });
});

digestSchema.virtual("month").get(function getMonth() {
  return new Date(this.sentAt).toLocaleDateString(undefined, { month: "long", year: "numeric" });
});

digestSchema.set("toJSON", {
  virtuals: true,
  transform(_doc, ret) {
    ret.id = ret._id;
    delete ret._id;
    delete ret.__v;
    ret.date = ret.sentAt;
    return ret;
  },
});

export default mongoose.model("Digest", digestSchema);